[workspace]
members = [
    "plant-wate-rs-core",
    "plant-wate-rs-esp32c3",
]
resolver = "2"

[profile.release]
opt-level = "s"
codegen-units = 1
lto = true

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
